### ISSUE TITLE
Search + Internal Server Error

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/marshall_webapp_wiki#125]
Just a quick comment.  It seems that when two people do a search simultaneously, that's when the internal server error is triggered.  We then have to wait until the server restart for it to function again.

**Comment by thespacedoctor** [comment]
thanks for all the enhancement suggestions Ken - these are very useful!
This bug is especially interesting - would love to get this killed off for
good!

cheers,
Dave

------------------------------
*Dr. David Young* (Scientific Programmer)
*e:* d.r.young@qub.ac.uk
*a:* Astrophysics Research Centre, School of Mathematics and Physics,
Queen's University Belfast, Belfast, BT7 1NN, UK
*t:* (028) 90976362
*w:* http://psweb.mp.qub.ac.uk/dry/ <http://star.pst.qub.ac.uk/apollo/>

**Comment by genghisken** [comment]
OK. More diagnosis - seems that if I hit return x 2 when doing a search (i.e. search#1 does not complete before doing search#2), this also triggers the bug. (I guess that's equivalent to two people searching at the same time.)

**Comment by thespacedoctor** [comment]
thanks to your double return trick ken I was able to finally trace this bug down to a MySQLdb issue. MySQLdb cannot share a database connection across multiple threads. When users of the marshall are preforming almost-simultaneous actions (e.g. double hit return in the search field) the web-app tries to share the connection between threads and falls over.

I've switched all of my database interactions from the web-app across from MySQLdb to sqlalchemy and all now seems right with the world ...  well at least the double return trick doesn't break the marshall. 

I hope this is a permanent fix. Will check the marshall logs over the next few days to see if this issue has finally disappeared.
