### ISSUE TITLE
Association with host not labelled e.g. AT2017efr

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/marshall_webapp_wiki#132]
AT2017efr is to be associated with GALEXASC J223112.25-260054.8 correctly by sherlock, since it is given SN designation. 

But is not specifically stated in the marshall. All it says is "SN"
Should say something like 
"X arcsec from UV source GALEXASC J223112.25-260054.8. Likely SN" 

Clearly this GALEX source is an extended Pan-STARRS source too. But we are not searching that catalogue yet.

Although when I try to update the marhsall context info box, I get an "Internal Server Error"  !
And doesn't let me submit

**Comment by thespacedoctor** [comment]
The issue with not being able to add a comment was due to your comment being too long for the column size I had assigned in the marshall database. I've increase the column size from a 100 to a 500 character limit and added your comment to AT2017efr.

http://www.pessto.org/marshall/transients/7182200

**Comment by thespacedoctor** [comment]
I'm aware of the issue of transients getting classified but with missing crossmatch info. It seems for a few objects the crossmatch info fails to get injected into the `sherlock_crossmatches` table. I think the issue is arising from a database deadlock whenever there are multiple writes occurring at the same time.

**Comment by thespacedoctor** [comment]
This issue has gone away with recent updates to Sherlock.
