### ISSUE TITLE
Updated data for AT\SN2017jei not retrieved from TNS

### ISSUE THREAD

**Issue by Lightbulb500** [thespacedoctor/marshall_webapp_wiki#152]
SN2017jei is classified as a Type II SN with an IAU name on the TNS

The Marshall however still reports it as an AT with no classification information

**Comment by thespacedoctor** [comment]
Oddly enough this is expected behaviour!

Transients classified by ePESSTO are NOT imported via the TNS so that the data reduction team can add more detail of the classification via the marshall's classification form (such as phase info). 

You need to click the 'target' but to bring up the classification form:

![screengrab][screengrab 40377855022]

[screengrab 40377855022]: https://farm5.staticflickr.com/4649/40377855022_95bbeae961_o.png 

and then update the classification information. Make sure to select ePESSTO as the source. Once a SN classification is given the name *should* switch. 

Once the ePESSTO ATels come out I always check the classification information in the marshall and update it where appropriate anyway ... but this one didn't get an updated ATel  ;)
