### ISSUE TITLE
Proxy error when adding a new ticket

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/marshall_webapp_wiki#156]
Seems like Paolo and I both get a Proxy error when adding new ticket

**Comment by thespacedoctor** [comment]
Think this issue is related to #157. Once I remove the offending SQL process I was able to add a new test source to the inbox without proxy errors.

Assuming it was the GRB you were adding:

http://www.pessto.org/marshall/transients/search?q=GRB180504A

I removed a duplicate with almost the same name: GRB18054A
