### ISSUE TITLE
ATLAS18nnf not recognised as SN2018ard

### ISSUE THREAD

**Issue by Lightbulb500** [thespacedoctor/marshall_webapp_wiki#159]
ATLAS18nnf has appeared in the [Marshall](url) as a duplicate object of SN2018ard.

They are both correctly associated on both the [ATLAS pages](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1133119600331354200/) and the [TNS](https://wis-tns.weizmann.ac.il/object/2018ard)

**Comment by thespacedoctor** [comment]
Ok so it took me all afternoon to track down the issue here. The flow of events to cause the duplication was:

1. ASASSN discovered the source and reported to TNS with completely the wrong coordinates
2. Marshall imports from TNS
3. ASASSN silently correct the coordinates on TNS
4. Marshall pulls in corrected coordinates for subsequent reports to TNS but continues to use the initial incorrect coordinates for future crossmatches
5. ATLAS FP comes into Marshall and a crossmatch misses the original source in Marshall because coordinates are wrong and hence duplication

See the comments at the bottom of TNS page:

https://wis-tns.weizmann.ac.il/object/2018ard

**Comment by thespacedoctor** [comment]
Force photometry now correctly associated and duplicate removed:

http://www.pessto.org/marshall/transients/search?q=ATLAS18nnf
