### ISSUE TITLE
ATel links have fallen over

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/marshall_webapp_wiki#167]
Recent objects in ATels are not being caught with the automatic ATel recogniser - very useful link!

**Comment by genghisken** [comment]
The ATLAS and Pan-STARRS apps both read their ATel data from the Marshall.  It doesn't appear to be working for recent ATels.

**Comment by genghisken** [comment]
On further investigation, it appears that the last ATel ingested into the marshall database was 11803. So the code fell over on 1st July 2018, and nothing has been ingested since then.  This means that the marshall can't see clearly which targets have already been classified by other surveys.

**Comment by thespacedoctor** [comment]
back in business:

![screengrab](https://farm2.staticflickr.com/1851/29444951397_72480a99f8_o.png)

**Comment by genghisken** [comment]
ATel links still not working on ATLAS + Pan-STARRS.  This is because the htmID16 and htmID20 fields are not being populated.  Can we get them retrospectively generated.  Same goes for other tables that contain these fields.  I think I've stopped using htmID20, but I still need htmID16 at minimum if the column exists in the feeder survey table.

**Comment by thespacedoctor** [comment]
Levels 10, 13, and 16 are now getting added to the `atel_coordinates` table. Do you also query the atel_names table? You'll probably squeeze a few more matches out of that table too.
