### ISSUE TITLE
Keep objects in the classification queue even if they have been classified externally

### ISSUE THREAD

**Issue by thespacedoctor** [thespacedoctor/marshall_webapp_wiki#182]
There have been cases where interesting sources have been removed from the classification queue when classified externally. The 'review for followup' queue then becomes a blind-spot for interesting sources.

**ACTIONS**

- externally classified sources to remain in the classification queue
- review for followup to be cleared on request from TAT (alongside inbox) before sub-runs.

**Comment by smarttgit** [comment]
I think this is the way forward - we caught one recently 2022epu, which was moved out of Classification Queue, due to classification being "SN" so the TAT didn't look at it. In the past it would have been assessed, as we used to clear out the "Review for follow-up" regularly. I think with the SEDM machine (not actually the reason for this one, but is a broader point) there are a lot of rough classifications that need a look at, and either we repeat with EFOSC2 or decide its interesting and more data needed. So I would leave in Classification Queue and let the TAT assess -  then some human eyes make a call.

**Comment by thespacedoctor** [comment]
Objects should now remain in the "classification targets" and "queued for classification" even with an external classification, requiring human/TAT intervention to move them "archive" or "followup".

Also, I have added the 'review to follow' queue to my cleanup script. If asked by the TAT I will now remove objects fainter the 20th mag and/or older than 4 weeks from this queue.
